version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./planner.db:/app/planner.db
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8081:8081"
    depends_on:
      - backend
    restart: always